URL_SERVICE = "https://f9592538-8fbd-45c8-b5c4-9193035c481e.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_KITS_PATH = "/api/v1/products/kits/"
СREATE_MAIN_KITS = "/api/v1/kits"
CREATE_USER_PATH = "/api/v1/users/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
